[phases.setup]
  nixPkgs = ['python3', 'python3Packages.pip']

[phases.build]
  cmds = ['pip install -r requirements.txt']

[phases.run]
  cmds = ['uvicorn src.api:app --host 0.0.0.0 --port $PORT --no-access-log']
